version: 2.1

jobs:
  pack:
    docker:
      - image: node:16

    steps:
      - checkout

      # Build and pack the application
      - run:
          name: Build and Pack
          command: |
            npm install
            npm run build
            tar -zcvf site.tgz build

      # Send the zip file to the server
      - deploy:
          name: Deploy to Server
          command: |
            scp -o StrictHostKeyChecking=no site.tgz $REMOTE_USER@$REMOTE_SERVER:/tmp/site.tgz

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - pack:
          filters:
            branches:
              only:
                - master  